---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: etcdops-manager
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - backupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - backupschedules/finalizers
  verbs:
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - backupschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - members
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - members/finalizers
  verbs:
  - update
- apiGroups:
  - operator.etcd.io
  resources:
  - members/status
  verbs:
  - get
  - patch
  - update
