apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcdops-manager
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcdops-manager-bindings
  namespace: default
subjects:
- kind: ServiceAccount
  name: etcdops-manager
  namespace: default
roleRef:
  kind: ClusterRole
  name: etcdops-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: etcdops-issuer
spec:
  selfSigned: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcdops
  namespace: default
  labels:
    app: etcdops
spec:
  selector:
    matchLabels:
      app: etcdops
  template:
    metadata:
      labels:
        app: etcdops
    spec:
      serviceAccountName: etcdops-manager
      containers:
        - name: etcdops
          image: cr.yandex/crpj9v5sqvlclb1os12m/etcdops:latest
          args: ["--cluster-issuer", "etcdops-issuer"]
